
services:
  stats-server:
    build: stats-service/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    volumes:
      - ewm_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  ewm-service:
      build:
         context: ewm-service
      container_name: ewm-service-container
      ports:
        - "8080:8080"
      depends_on:
        - ewm-db
        - stats-server
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        STATS_SERVICE_URL: http://stats-server:9090

volumes:
  stats_db_data:
  ewm_db_data:
